from polygoncreate import *

"""
An aggregation of all graphing functions
"""
#1. Graph a PolygonCreate instance, and all its children (if there are any). Returns None   
        #Add an attribute 'isoffset' to PolygonCreate class. Defaults to None,
        #but the polygon generated by polygon_offset should have a link back to the original polygon
        #This should be just the polygon, offset polygon, and any children
        #Make sure to add plot title, axis, ticks, legend indicating which one is offset which one is original, etc.
#2. Graph a Path instance
        #Graph the baseline, path, and its parent polygons (can reuse the function above)
        #Make sure to add plot title, axis, ticks, legend indicating which one is offset which one is original, etc.
#3. Graph a Path using stem plot.
        #Takes in a path and a second input in the form of an iterable with the same length as the number of lines in Path.
        #The second argument can be velocity, or height, etc as example. use that to generate a 3D plot using matplotlib.